version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    command: python /app/manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12
    env_file: ./.env.db